#!/usr/bin/perl

if(scalar(@ARGV) == 1) {
    my $first_arg = shift(@ARGV);
    my @u_a = split(/@/, $first_arg);

    if (defined $u_a[1]) {
        exec ("/usr/bin/ssh $u_a[0]\@$u_a[1] ", @ARGV);
    } else {
        print "Enter your username: ";
        my $username = <STDIN>;
        chomp ( $username );
        exec ("/usr/bin/ssh $username\@$u_a[0] ", @ARGV);
    }
} else {
    exec ("/usr/bin/ssh", @ARGV);
}
